### PR TITLE
New vectorised diffusion

### PR DESCRIPTION
**Pull request by MGretton**

### CODE REVIEW

**Comment by MGretton** [comment]
Hi Henrik, I've implemented the new vectorised diffusion methods. It's passing the unit tests and R CMD CHECK, but you should take a look. Thanks!

**Comment by singmann** [comment]
Hi Matthew,
I just ran the package checks on your version (i.e., `test()`, see `development.R` line 20) and it gives me an error in the `rrd` function. The following should work I guess. 

    > rrd(10, a=1, z=0.5, v=2, t0=0.5, d=0, sz = 0, sv = 0, st0 = 0)
    Error in rrd(10, a = 1, z = 0.5, v = 2, t0 = 0.5, d = 0, sz = 0, sv = 0,  : 
      object 'params' not found

Can you replicate that? If so, can you fix it?

**Comment by MGretton** [comment]
Hi Henrik, can confirm there's a problem. Not sure what's happened, but I think I've committed the wrong version somehow. Looking into it now.

**Comment by MGretton** [comment]
Hi Henrik, think I've solved those issues. Apologies for that, please try again (it passes R CMD CHECK on my machine).

**Comment by singmann** [comment]
Great. Thanks. Will perform further checks in the next time.

**Pull request merged**
